version: '2.4'

services:
  test_dbcontext:
    build:
      context: .
    ports:
      - '5000:80'
    depends_on:
      - db
  db:
    image: postgres:10
    restart: always
    env_file:
      - postgres.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
